### ISSUE TITLE
aligned_alloc seems to be not captured by this

### ISSUE THREAD

**Issue by horde3d** [itaych/MEM_debug#1]
I just tried your great memory checker, but got a _prefix broken_ error on memory allocated with aligned_alloc (https://en.cppreference.com/w/c/memory/aligned_alloc) as soon as one tries to free this block. 

Can the aligned_alloc call also be replaced with the allocation function defined in MEM_debug.cpp?

**Comment by horde3d** [comment]
To answer my own question, yes one can:

https://gist.github.com/horde3d/5019b019d1a5f9eb8c9f1cb1d0507353

**Comment by itaych** [comment]
Your patch is integrated in the 1.0.15 release, thanks! Apologies for not responding sooner.
